---
abstract: 'Insert POD from Rinci metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::More: 0.88
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Plugin-Perinci
requires:
  Perinci::To::POD: 0.30
  Pod::Weaver: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Pod-Weaver-Plugin-Perinci/
  repository: http://github.com/sharyanto/perl-Pod-Weaver-Plugin-Perinci
version: 0.12
